# Generated by Django 4.0.6 on 2022-07-17 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('idIngredientes', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60)),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('idPesoTipo', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idReceta', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rendimiento', models.CharField(max_length=20)),
                ('totalCost', models.IntegerField()),
                ('desc_receta', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Preparacion',
            fields=[
                ('idPreparacion', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('idIngredientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooking_base_app.ingredientes')),
                ('idPesoTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooking_base_app.peso')),
                ('idReceta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooking_base_app.receta')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='idPesoTipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooking_base_app.peso'),
        ),
    ]
